=== daniel-abella/exemplos/trunk/java/questoes/questoes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation source="pt_BR">Questões sobre Java Copyright (c) 2003 Fábio Nogueira de Lucena. TODOS OS DIREITOS RESERVADOS.        </xsd:documentation>
	</xsd:annotation>
	<xsd:element name="Avaliacao">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="avaliacaoTipo"/>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="avaliacaoTipo">
		<xsd:sequence>
			<xsd:element name="questao" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="questaoTipo"/>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="historicoTipo">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="evento" type="eventoHistoricoTipo"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="eventoHistoricoTipo">
		<xsd:sequence>
			<xsd:element name="pagina" type="xsd:positiveInteger" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="comentario" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="data" type="xsd:date" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="questaoTipo">
		<xsd:sequence>
			<xsd:element name="introducao" type="textoTipo"/>
			<xsd:element name="resposta">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="textoTipo">
							<xsd:attribute name="valor" type="xsd:string" use="required"/>
						</xsd:extension>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:positiveInteger" use="required"/>
		<xsd:attribute name="qi" type="xsd:positiveInteger" use="optional" default="1"/>
		<xsd:attribute name="tipo" use="optional" default="lógico">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string"/>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="objetivo" type="xsd:string" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="identificacaoTipo">
		<xsd:sequence>
			<xsd:element name="titulo" type="xsd:string"/>
			<xsd:element name="copyright" type="xsd:string"/>
			<xsd:element name="versao" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="textoTipo" mixed="true">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="stmt" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="java" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="it" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="bd" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:element name="stmt"/>
	<xsd:element name="java"/>
	<xsd:element name="it"/>
	<xsd:element name="bd"/>
	<xsd:element name="link"/>
</xsd:schema>

=== daniel-abella/exemplos/java/questoes/java-arrays.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="questoes.xslt"?>
<Avaliacao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="questoes.xsd">
	<identificacao>
		<titulo>Linguagem de Programação Java</titulo>
		<copyright>Fábio Nogueira de Lucena</copyright>
		<versao>1.0</versao>
	</identificacao>
	<historico>
		<evento data="2003-10-07">
			<comentario>Atingido o total de 2071 questões!</comentario>
		</evento>
	</historico>


<questao id="0" objetivo="1.1">
	<introducao>O código abaixo compila satisfatoriamente.<java><![CDATA[public class Array13 {
    public static void mostraArray(int[] array) {
        if (array == null) {
            return;
        }

        for (int i = 0; i < array.length; i++) {
            System.out.println(array[i]);
        }
    }

    public static void main(String[] args) {
        mostraArray(new int[] { 1, 2, new byte[] { 1 }[0], 4 });
    }
}]]></java></introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

<questao id="0" objetivo="1.1">
	<introducao>
	</introducao>
	<resposta valor="v">
	</resposta>
</questao>

</Avaliacao>
